// Division 3 schools with lacrosse programs

export const d3Schools = [
    { name: "Adrian College", file: "adrian_college.json", color: "#003087", secondaryColor: "#FFB81C" },
    { name: "Albertus Magnus College", file: "albertus_magnus_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Albion College", file: "albion_college.json", color: "#8B0000", secondaryColor: "#C0A060" },
    { name: "Albright College", file: "albright_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Alfred State College", file: "alfred_state_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Alfred University", file: "alfred_university.json", color: "#4B0082", secondaryColor: "#C0A060" },
    { name: "Allegheny College", file: "allegheny_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Alma College", file: "alma_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Alvernia University", file: "alvernia_university.json", color: "#8B0000", secondaryColor: "#C0A060" },
    { name: "Amherst College", file: "amherst_college.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "Anderson University - Indiana", file: "anderson_university_indiana.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Anna Maria College", file: "anna_maria_college.json", color: "#004B87", secondaryColor: "#C0A060" },
    { name: "Arcadia University", file: "arcadia_university.json", color: "#C0A060", secondaryColor: "#004B87" },
    { name: "Augustana College - Illinois", file: "augustana_college_illinois.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Aurora University", file: "aurora_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Averett University", file: "averett_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Babson College", file: "babson_college.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Baldwin Wallace University", file: "baldwin_wallace_university.json", color: "#FFB81C", secondaryColor: "#000000" },
    { name: "Bates College", file: "bates_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Beloit College", file: "beloit_college.json", color: "#C0A060", secondaryColor: "#003087" },
    { name: "Benedictine University", file: "benedictine_university.json", color: "#004B87", secondaryColor: "#808080" },
    { name: "Berry College", file: "berry_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Bethany College - West Virginia", file: "bethany_college_west_virginia.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Bowdoin College", file: "bowdoin_college.json", color: "#000000", secondaryColor: "#808080" },
    { name: "Brevard College", file: "brevard_college.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Bridgewater College", file: "bridgewater_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Bryn Athyn College", file: "bryn_athyn_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Cairn University", file: "cairn_university.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Calvin University", file: "calvin_university.json", color: "#8B0000", secondaryColor: "#C0A060" },
    { name: "Capital University", file: "capital_university.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Carroll University", file: "carroll_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Carthage College", file: "carthage_college.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Catholic University of America", file: "catholic_university_of_america.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Centenary College of Louisiana", file: "centenary_college_of_louisiana.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Centenary University - New Jersey", file: "centenary_university_new_jersey.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Centre College", file: "centre_college.json", color: "#C0A060", secondaryColor: "#000000" },
    { name: "Chatham University", file: "chatham_university.json", color: "#004B87", secondaryColor: "#808080" },
    { name: "Christopher Newport University", file: "christopher_newport_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Clark University", file: "clark_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Clarkson University", file: "clarkson_university.json", color: "#006747", secondaryColor: "#C0A060" },
    { name: "Colby College", file: "colby_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "College of Wooster", file: "college_of_wooster.json", color: "#000000", secondaryColor: "#C0A060" },
    { name: "Colorado College", file: "colorado_college.json", color: "#000000", secondaryColor: "#C0A060" },
    { name: "Concordia University Wisconsin", file: "concordia_university_wisconsin.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Connecticut College", file: "connecticut_college.json", color: "#000000", secondaryColor: "#808080" },
    { name: "Cornell College", file: "cornell_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Curry College", file: "curry_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Dean College", file: "dean_college.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Delaware Valley University", file: "delaware_valley_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Denison University", file: "denison_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "DePauw University", file: "depauw_university.json", color: "#FFB81C", secondaryColor: "#000000" },
    { name: "DeSales University", file: "desales_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Dickinson College", file: "dickinson_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Drew University", file: "drew_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Earlham College", file: "earlham_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Eastern Connecticut State University", file: "eastern_connecticut_state_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Eastern University", file: "eastern_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Edgewood College", file: "edgewood_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Elizabethtown College", file: "elizabethtown_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Elmhurst University", file: "elmhurst_university.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "Elmira College", file: "elmira_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Elms College", file: "elms_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Emerson College", file: "emerson_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Emmanuel College - Massachusetts", file: "emmanuel_college_massachusetts.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Endicott College", file: "endicott_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Fairleigh Dickinson University - College at Florham", file: "fairleigh_dickinson_university_college_at_florham.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Franciscan University of Steubenville", file: "franciscan_university_of_steubenville.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Franklin & Marshall College", file: "franklin_marshall_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Gettysburg College", file: "gettysburg_college.json", color: "#FF6600", secondaryColor: "#003087" },
    { name: "Gordon College", file: "gordon_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Goucher College", file: "goucher_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Greensboro College", file: "greensboro_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Grove City College", file: "grove_city_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Guilford College", file: "guilford_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Gwynedd Mercy University", file: "gwynedd_mercy_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Hamilton College", file: "hamilton_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Hampden-Sydney College", file: "hampden_sydney_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Hanover College", file: "hanover_college.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Hartwick College", file: "hartwick_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Haverford College", file: "haverford_college.json", color: "#000000", secondaryColor: "#808080" },
    { name: "Heidelberg University", file: "heidelberg_university.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Hendrix College", file: "hendrix_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Hilbert College", file: "hilbert_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Hiram College", file: "hiram_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Hobart & William Smith College", file: "hobart_william_smith_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Hood College", file: "hood_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Hope College", file: "hope_college.json", color: "#FF6600", secondaryColor: "#003087" },
    { name: "Huntingdon College", file: "huntingdon_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Husson University", file: "husson_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Illinois Institute of Technology", file: "illinois_institute_of_technology.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Illinois Wesleyan University", file: "illinois_wesleyan_university.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Immaculata University", file: "immaculata_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Ithaca College", file: "ithaca_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "John Carroll University", file: "john_carroll_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Johnson & Wales University - Providence", file: "johnson_wales_university_providence.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Juniata College", file: "juniata_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Kalamazoo College", file: "kalamazoo_college.json", color: "#FF6600", secondaryColor: "#000000" },
    { name: "Kean University", file: "kean_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Keene State College", file: "keene_state_college.json", color: "#FFB81C", secondaryColor: "#000000" },
    { name: "Kenyon College", file: "kenyon_college.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "Keuka College", file: "keuka_college.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Keystone College", file: "keystone_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "King's College - Pennsylvania", file: "king_s_college_pennsylvania.json", color: "#C0A060", secondaryColor: "#003087" },
    { name: "La Roche University", file: "la_roche_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "LaGrange College", file: "lagrange_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Lake Forest College", file: "lake_forest_college.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Lasell University", file: "lasell_university.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Lawrence University", file: "lawrence_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Lebanon Valley College", file: "lebanon_valley_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Lycoming College", file: "lycoming_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Maine Maritime Academy", file: "maine_maritime_academy.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Manhattanville College", file: "manhattanville_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Marian University - Wisconsin", file: "marian_university_wisconsin.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Marietta College", file: "marietta_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Marymount University", file: "marymount_university.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Marywood University", file: "marywood_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Massachusetts College of Liberal Arts", file: "massachusetts_college_of_liberal_arts.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "Massachusetts Institute of Technology", file: "mit.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Massachusetts Maritime Academy", file: "massachusetts_maritime_academy.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "McDaniel College", file: "mcdaniel_college.json", color: "#006747", secondaryColor: "#C0A060" },
    { name: "Messiah University", file: "messiah_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Methodist University", file: "methodist_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Middlebury College", file: "middlebury_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Milwaukee School of Engineering", file: "milwaukee_school_of_engineering.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Misericordia University", file: "misericordia_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Mitchell College", file: "mitchell_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Montclair State University", file: "montclair_state_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Moravian University", file: "moravian_university.json", color: "#808080", secondaryColor: "#000000" },
    { name: "Mount Saint Mary College - New York", file: "mount_saint_mary_college_new_york.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Mount St. Joseph University", file: "mount_st_joseph_university.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Muhlenberg College", file: "muhlenberg_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Muskingum University", file: "muskingum_university.json", color: "#000000", secondaryColor: "#808080" },
    { name: "Nazareth University", file: "nazareth_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Neumann University", file: "neumann_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "New England College", file: "new_england_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Nichols College", file: "nichols_college.json", color: "#006747", secondaryColor: "#C0A060" },
    { name: "North Central College", file: "north_central_college.json", color: "#CC0000", secondaryColor: "#C0A060" },
    { name: "Northland College", file: "northland_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Norwich University", file: "norwich_university.json", color: "#CC0000", secondaryColor: "#C0A060" },
    { name: "Oberlin College", file: "oberlin_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Oglethorpe University", file: "oglethorpe_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Ohio Northern University", file: "ohio_northern_university.json", color: "#FF6600", secondaryColor: "#000000" },
    { name: "Ohio Wesleyan University", file: "ohio_wesleyan_university.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Otterbein University", file: "otterbein_university.json", color: "#CC0000", secondaryColor: "#C0A060" },
    { name: "Pennsylvania College of Technology", file: "pennsylvania_college_of_technology.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Pfeiffer University", file: "pfeiffer_university.json", color: "#000000", secondaryColor: "#C0A060" },
    { name: "Piedmont University", file: "piedmont_university.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Plymouth State University", file: "plymouth_state_university.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Randolph College", file: "randolph_college.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Randolph-Macon College", file: "randolph_macon_college.json", color: "#FFB81C", secondaryColor: "#000000" },
    { name: "Regis College", file: "regis_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Rensselaer Polytechnic Institute", file: "rpi.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Rhodes College", file: "rhodes_college.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Rivier University", file: "rivier_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Roanoke College", file: "roanoke_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Rochester Institute of Technology", file: "rochester_institute_of_technology.json", color: "#F36E21", secondaryColor: "#000000" },
    { name: "Roger Williams University", file: "roger_williams_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Rosemont College", file: "rosemont_college.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "Russell Sage College", file: "russell_sage_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Saint Joseph's College of Maine", file: "saint_joseph_s_college_of_maine.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Saint Vincent College - Pennsylvania", file: "saint_vincent_college_pennsylvania.json", color: "#006747", secondaryColor: "#C0A060" },
    { name: "Salem State University", file: "salem_state_university.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Salisbury University", file: "salisbury_university.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Salve Regina University", file: "salve_regina_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Sewanee - The University of the South", file: "sewanee_the_university_of_the_south.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Shenandoah University", file: "shenandoah_university.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "Skidmore College", file: "skidmore_college.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Southern Virginia University", file: "southern_virginia_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Southwestern University", file: "southwestern_university.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Spalding University", file: "spalding_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Springfield College", file: "springfield_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "St. John Fisher College", file: "st_john_fisher_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "St. Lawrence University", file: "st_lawrence_university.json", color: "#CC0000", secondaryColor: "#8B4513" },
    { name: "St. Mary's College of Maryland", file: "st_mary_s_college_of_maryland.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Stevens Institute of Technology", file: "stevens_institute_of_technology.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Stevenson University", file: "stevenson_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Stockton University", file: "stockton_university.json", color: "#006747", secondaryColor: "#808080" },
    { name: "SUNY Canton", file: "suny_canton.json", color: "#003087", secondaryColor: "#808080" },
    { name: "SUNY College at Brockport", file: "suny_college_at_brockport.json", color: "#006747", secondaryColor: "#C0A060" },
    { name: "SUNY College at Oneonta", file: "suny_college_at_oneonta.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "SUNY Cobleskill", file: "suny_cobleskill.json", color: "#006747", secondaryColor: "#FFB81C" },
    { name: "SUNY Cortland", file: "suny_cortland.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "SUNY Delhi", file: "suny_delhi.json", color: "#006747", secondaryColor: "#808080" },
    { name: "SUNY Farmingdale", file: "suny_farmingdale.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "SUNY Geneseo", file: "suny_geneseo.json", color: "#003087", secondaryColor: "#808080" },
    { name: "SUNY Maritime College", file: "suny_maritime_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "SUNY Morrisville", file: "suny_morrisville.json", color: "#006747", secondaryColor: "#FFB81C" },
    { name: "SUNY New Paltz", file: "suny_new_paltz.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "SUNY Oswego", file: "suny_oswego.json", color: "#006747", secondaryColor: "#808080" },
    { name: "SUNY Plattsburgh", file: "suny_plattsburgh.json", color: "#006747", secondaryColor: "#808080" },
    { name: "SUNY Polytechnic Institute", file: "suny_polytechnic_institute.json", color: "#003087", secondaryColor: "#808080" },
    { name: "SUNY Potsdam", file: "suny_potsdam.json", color: "#006747", secondaryColor: "#808080" },
    { name: "SUNY Purchase College", file: "suny_purchase_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Susquehanna University", file: "susquehanna_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Swarthmore College", file: "swarthmore_college.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "Thiel College", file: "thiel_college.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Thomas College", file: "thomas_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Transylvania University", file: "transylvania_university.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Trine University", file: "trine_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Trinity College - Connecticut", file: "trinity_college_connecticut.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Tufts University", file: "tufts_university.json", color: "#003087", secondaryColor: "#8B4513" },
    { name: "Union College - New York", file: "union_college_new_york.json", color: "#8B0000", secondaryColor: "#808080" },
    { name: "United States Coast Guard Academy", file: "united_states_coast_guard_academy.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "United States Merchant Marine Academy", file: "united_states_merchant_marine_academy.json", color: "#003087", secondaryColor: "#808080" },
    { name: "University of Dubuque", file: "university_of_dubuque.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "University of Hartford", file: "university_of_hartford.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "University of Lynchburg", file: "university_of_lynchburg.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "University of Mary Washington", file: "university_of_mary_washington.json", color: "#CC0000", secondaryColor: "#003087" },
    { name: "University of Massachusetts - Boston", file: "umass_boston.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "University of Mount Saint Vincent", file: "university_of_mount_saint_vincent.json", color: "#003087", secondaryColor: "#808080" },
    { name: "University of Mount Union", file: "university_of_mount_union.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "University of New England", file: "university_of_new_england.json", color: "#003087", secondaryColor: "#808080" },
    { name: "University of Pittsburgh - Bradford", file: "university_of_pittsburgh_bradford.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "University of Saint Joseph", file: "university_of_saint_joseph.json", color: "#003087", secondaryColor: "#808080" },
    { name: "University of Scranton", file: "university_of_scranton.json", color: "#461F79", secondaryColor: "#808080" },
    { name: "University of Southern Maine", file: "university_of_southern_maine.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Ursinus College", file: "ursinus_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Utica University", file: "utica_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Vassar College", file: "vassar_college.json", color: "#808080", secondaryColor: "#CC0000" },
    { name: "Vermont State University - Castleton", file: "vermont_state_university_castleton.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Vermont State University - Lyndon", file: "vermont_state_university_lyndon.json", color: "#006747", secondaryColor: "#808080" },
    { name: "Virginia Wesleyan University", file: "virginia_wesleyan_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Wabash College", file: "wabash_college.json", color: "#CC0000", secondaryColor: "#808080" },
    { name: "Warren Wilson College", file: "warren_wilson_college.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Washington & Jefferson College", file: "washington_jefferson_college.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Washington & Lee University", file: "washington_lee_university.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Washington College", file: "washington_college.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Wentworth Institute of Technology", file: "wentworth_institute_of_technology.json", color: "#003087", secondaryColor: "#CC0000" },
    { name: "Wesleyan University", file: "wesleyan_university.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "Western Connecticut State University", file: "western_connecticut_state_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Western New England University", file: "western_new_england_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Westminster College - Pennsylvania", file: "westminster_college_pennsylvania.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Wheaton College - Massachusetts", file: "wheaton_college_massachusetts.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Widener University", file: "widener_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "Wilkes University", file: "wilkes_university.json", color: "#003087", secondaryColor: "#C0A060" },
    { name: "William Peace University", file: "william_peace_university.json", color: "#003087", secondaryColor: "#808080" },
    { name: "Williams College", file: "williams_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Wilmington College", file: "wilmington_college.json", color: "#461F79", secondaryColor: "#C0A060" },
    { name: "Wittenberg University", file: "wittenberg_university.json", color: "#CC0000", secondaryColor: "#000000" },
    { name: "York College of Pennsylvania", file: "york_college_of_pennsylvania.json", color: "#006747", secondaryColor: "#808080" },
];

export function searchD3Schools(query) {
    if (!query) return d3Schools;
    const lowerQuery = query.toLowerCase();
    return d3Schools.filter(s => s.name.toLowerCase().includes(lowerQuery));
}

export function getD3FileForTeam(teamName) {
    const school = d3Schools.find(s => s.name.toLowerCase() === teamName.toLowerCase());
    return school ? school.file : null;
}

export function getD3SchoolData(teamName) {
    if (!teamName) return null;
    return d3Schools.find(s => s.name.toLowerCase() === teamName.toLowerCase()) || null;
}
